basic.forever(function () {
    cuteBot.forward()
    basic.pause(200)
    cuteBot.turnright()
    basic.pause(200)
    cuteBot.forward()
    basic.pause(200)
    cuteBot.turnright()
    basic.pause(200)
    cuteBot.stopcar()
    basic.pause(2000)
})
